MvcStok/MvcStok/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;

namespace MvcStok.Controllers
{
    public class KategoriController : Controller
    {
        // GET: Kategori
        DbMvcStokEntities db=new DbMvcStokEntities();
        public ActionResult Index()
        {
            var ktgr = db.TblKategori.ToList();

            return View(ktgr);
        }

        [HttpGet]
        public ActionResult YeniEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniEkle(TblKategori kategori)
        {
            db.TblKategori.Add(kategori);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Sil(int id)
        {
            
            var ktgr= db.TblKategori.Find(id);
            db.TblKategori.Remove(ktgr);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Getir(int id)
        {
            var kategori = db.TblKategori.Find(id);
            return View(kategori);
        }

        [HttpPost]
        public ActionResult Guncelle(TblKategori kategori)
        {
            var ktgr = db.TblKategori.Find(kategori.id);
            ktgr.ad = kategori.ad;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcStok/MvcStok/Views/Kategori/Getir.cshtml
@model MvcStok.Models.Entity.TblKategori
@{
    ViewBag.Title = "Getir";
    Layout = "~/Views/Shared/_adminlayout.cshtml";
}

<h1>Kategori Güncelleme</h1>
@using (Html.BeginForm("Guncelle", "Kategori", FormMethod.Post))
{
    <br />
    @Html.TextBoxFor(m => m.ad, new { @class = "form-control" })
    <button class="btn btn-info" style="margin-top:10px">Guncelle</button>
    @Html.HiddenFor(m=>m.id)
}

MvcStok/MvcStok/Views/Kategori/Index.cshtml
@using MvcStok.Models.Entity
@model List<TblKategori>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_adminlayout.cshtml";
}

<h1>Kategori Menü</h1>
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Kategori Ad</th>
        <th>İşlemler</th>
    </tr>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.id</td>
                <td>@item.ad</td>
                <td><a href="/Kategori/Sil/@item.id" class="btn btn-danger">Sil</a>  <a href="/Kategori/Getir/@item.id" class="btn btn-success">Güncelle</a></td>
            </tr>
        }
    </tbody>
</table>
<a href="/Kategori/YeniEkle" class="btn btn-primary">Yeni Kategori</a>

MvcStok/MvcStok/Views/Kategori/YeniEkle.cshtml
@{
    ViewBag.Title = "YeniEkle";
    Layout = "~/Views/Shared/_adminlayout.cshtml";
}
<h1>Yeni Kategori Ekleme</h1>
<form method="post">
    <br />
    <label>Kategori Ad</label>
    <input type="text" class="form-control" name="ad" placeholder="Kategori Ad" />
    <button class="btn btn-info" style="margin-top:10px">Ekle</button>
</form>