MvcStok/MvcStok/Controllers/UrunlerController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using MvcStok.Models.Entity;

namespace MvcStok.Controllers
{
    public class UrunlerController : Controller
    {
        // GET: Urunler
        DbMvcStokEntities db=new DbMvcStokEntities();
        public ActionResult Index(string p)
        {
            //var urunler=db.TblUrunler.Where(x=>x.durum==true).ToList();
            var urunler = from x in db.TblUrunler select x;
            if (!string.IsNullOrEmpty(p))
            {
                urunler = db.TblUrunler.Where(x => x.marka.Contains(p)||x.ad.Contains(p));   
            }
            return View(urunler.ToList());
        }
        public ActionResult KapaliUrunler()
        {
            var urunler=db.TblUrunler.Where(x=>x.durum==false).ToList();
            return View(urunler);
        }

        [HttpGet]
        public ActionResult YeniUrun()
        {
            List<SelectListItem> ktgr=(from x in db.TblKategori.ToList()
                                       select new SelectListItem
                                       {
                                           Text=x.ad,
                                           Value=x.id.ToString()
                                       }).ToList();
            ViewBag.drop = ktgr;
            return View();
        }

        [HttpPost]
        public ActionResult YeniUrun(TblUrunler urun)
        {
            
            var ktgr = db.TblKategori.Where(x => x.id == urun.TblKategori.id).FirstOrDefault();
            urun.TblKategori = ktgr;
            urun.durum = urun.stok > 0 ? true : false;
            db.TblUrunler.Add(urun);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Getir(int ID)
        {
            var urun = db.TblUrunler.Find(ID);
            List<SelectListItem> ktgr=(from x in db.TblKategori.ToList()
                                       select new SelectListItem
                                       {
                                           Text=x.ad,
                                           Value=x.id.ToString()
                                       }).ToList();
            ViewBag.drops=ktgr;
            return View("Getir",urun);
        }
        public ActionResult Guncelle(TblUrunler urun)
        {
            var ktgr = db.TblKategori.Where(x => x.id == urun.TblKategori.id).FirstOrDefault();
            var dburun = db.TblUrunler.Find(urun.id);
            dburun.TblKategori= ktgr;
            dburun.ad= urun.ad;
            dburun.marka= urun.marka;
            dburun.stok= urun.stok;
            dburun.alisfiyat= urun.alisfiyat;
            dburun.satisfiyat= urun.satisfiyat;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult UrunSil(TblUrunler urun)
        {
            var gelenurun = db.TblUrunler.Find(urun.id);
            gelenurun.durum = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Yenile(int ID)
        {
            
            var urun=db.TblUrunler.Find(ID);
            urun.durum =urun.stok>0? true:false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

MvcStok/MvcStok/Views/Urunler/Getir.cshtml
@model MvcStok.Models.Entity.TblUrunler
@{
    ViewBag.Title = "Getir";
    Layout = "~/Views/Shared/_adminlayout.cshtml";
}

<h1>Ürün Güncelleme</h1>
@using (Html.BeginForm("Guncelle", "Urunler", FormMethod.Post))
{

    <br />
    @Html.TextBoxFor(x=>x.ad,new{ @class="form-control"})
    
    <br />
    @Html.TextBoxFor(x=>x.marka,new{ @class="form-control"})
    
    <br />
    @Html.TextBoxFor(x=>x.stok,new{ @class="form-control"})
    
    <br />
    @Html.TextBoxFor(x=>x.alisfiyat,new{ @class="form-control"})
    
    <br />
    @Html.TextBoxFor(x=>x.satisfiyat,new{ @class="form-control"})
    
    <br />
    @Html.DropDownListFor(x => x.TblKategori.id, (List<SelectListItem>)ViewBag.drops, new {@class="form-control"})

    @Html.HiddenFor(x => x.id)
    <br />
    <button class="btn btn-warning">Güncelle</button>
}

MvcStok/MvcStok/Views/Urunler/Index.cshtml
@using MvcStok.Models.Entity
@model List<TblUrunler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_adminlayout.cshtml";
}

<h1>Ürünler Menü</h1>
<br />
@using (Html.BeginForm("Index", "Urunler", FormMethod.Get))
{
    <p>
        @Html.TextBox("p")
        <input class="btn btn-info" type="submit" value="Ara"/>
    </p>
}
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>İsim</th>
        <th>Marka</th>
        <th>Stok</th>
        <th>Alış Fiyatı</th>
        <th>Satış Fiyatı</th>
        <th>Kategori</th>
        <th>İşlemler</th>
    </tr>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.id</td>
                <td>@item.ad</td>
                <td>@item.marka</td>
                <td>@item.stok</td>
                <td>@item.alisfiyat ₺</td>
                <td>@item.satisfiyat ₺</td>
                <td>@item.TblKategori.ad</td>
                <td><a href="/Urunler/UrunSil/@item.id" class="btn btn-danger">Sil</a>  <a href="/Urunler/Getir/@item.id" class="btn btn-success">Güncelle</a></td>
            </tr>
        }
    </tbody>
</table>
<a href="/Urunler/YeniUrun" class="btn btn-primary">Yeni Ürün</a>
<a href="/Urunler/KapaliUrunler" class="btn btn-danger">Satışta olmayan Ürünler</a>

MvcStok/MvcStok/Views/Urunler/KapaliUrunler.cshtml
@using MvcStok.Models.Entity
@model List<TblUrunler>
@{
    ViewBag.Title = "KapaliUrunler";
    Layout = "~/Views/Shared/_adminlayout.cshtml";
}

<h1>Satışta Olmayan Ürünler</h1>
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Ad</th>
        <th>Marka</th>
        <th>Stok</th>
        <th>Alış Fiyatı</th>
        <th>Satış Fiyatı</th>
        <th>Kategori</th>
        <th>İşlemler</th>
    </tr>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.id</td>
                <td>@item.ad</td>
                <td>@item.marka</td>
                <td>@item.stok</td>
                <td>@item.alisfiyat ₺</td>
                <td>@item.satisfiyat ₺</td>
                <td>@item.TblKategori.ad</td>
                <td><a href="/Urunler/Yenile/@item.id" class="btn btn-success">Satışa Ekle</a></td>
            </tr>
        }
    </tbody>
</table>

MvcStok/MvcStok/Views/Urunler/YeniUrun.cshtml
@model MvcStok.Models.Entity.TblUrunler


@{
    ViewBag.Title = "YeniUrun";
    Layout = "~/Views/Shared/_adminlayout.cshtml";
}

<h1>Yeni Ürun</h1>
<form method="post">

    <label>İsim</label>
    @Html.TextBoxFor(x => x.ad, new { @class = "form-control" })
    <br />
    <label>Marka</label>
    @Html.TextBoxFor(x => x.marka, new { @class = "form-control" })
    <br />
    <label>Stok</label>
    @Html.TextBoxFor(x => x.stok, new { @class = "form-control" })
    <br />
    <label>Alış Fiyatı</label>
    @Html.TextBoxFor(x => x.alisfiyat, new { @class = "form-control" })
    <br />
    <label>Satış Fiyatı</label>
    @Html.TextBoxFor(x => x.satisfiyat, new { @class = "form-control" })
    <br />
    <label>Kategori</label>
    @Html.DropDownListFor(x => x.TblKategori.id, (List<SelectListItem>)ViewBag.drop, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Ekle</button>
</form>