MvcStok/MvcStok/Controllers/MusteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;
using PagedList;
using PagedList.Mvc;

namespace MvcStok.Controllers
{
    public class MusteriController : Controller
    {
        DbMvcStokEntities db=new DbMvcStokEntities();
        public ActionResult Index(int sayfa=1)
        {
            var musteriler=db.TblMusteriler.Where(m=>m.durum==true).ToList().ToPagedList(sayfa,5);
            return View(musteriler);
        }
        public ActionResult BakiyesizMusteriler(int sayfa=1)
        {
            var musteriler=db.TblMusteriler.Where(m=>m.durum==false).ToList().ToPagedList(sayfa,5);
            return View(musteriler);    
        }

        [HttpGet]
        public ActionResult YeniMusteri()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniMusteri(TblMusteriler musteri)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            musteri.durum = false;
            musteri.bakiye = 0;
            db.TblMusteriler.Add(musteri);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Sil(int id)
        {
            if (db.TblMusteriler.Find(id).bakiye > 0)
                return Index();
            else
            {
                db.TblMusteriler.Find(id).durum = false;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }
        public ActionResult MusteriGetir(int id)
        {
            var musteri = db.TblMusteriler.Find(id);
            return View("MusteriGetir",musteri);
        }
        public ActionResult MusteriGuncelle(TblMusteriler musteri)
        {
            var guncellenecek=db.TblMusteriler.Find(musteri.id);
            guncellenecek.ad=musteri.ad;
            guncellenecek.soyad=musteri.soyad;
            guncellenecek.sehir=musteri.sehir;
            guncellenecek.bakiye=musteri.bakiye;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcStok/MvcStok/Views/Musteri/BakiyesizMusteriler.cshtml
@using MvcStok.Models.Entity
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<TblMusteriler>
@{
    ViewBag.Title = "BakiyesizMusteriler";
    Layout = "~/Views/Shared/_adminlayout.cshtml";
}

<h1>Bakiyesiz Musteriler</h1>
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Şehir</th>
        <th>Bakiye</th>
        
    </tr>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.id</td>
                <td>@item.ad</td>
                <td>@item.soyad</td>
                <td>@item.sehir</td>
                <td>@item.bakiye ₺</td>
            </tr>
        }
    </tbody>
</table>
@Html.PagedListPager((IPagedList)Model, sayfa=> Url.Action("BakiyesizMusteriler", new {sayfa}))

MvcStok/MvcStok/Views/Musteri/Index.cshtml
@using MvcStok.Models.Entity
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<TblMusteriler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_adminlayout.cshtml";
}

<h1>Müşteri Menü</h1>
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Şehir</th>
        <th>Bakiye</th>
        <th>İşlemler</th>
    </tr>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.id</td>
                <td>@item.ad</td>
                <td>@item.soyad</td>
                <td>@item.sehir</td>
                <td>@item.bakiye ₺</td>
                <td><a href="/Musteri/Sil/@item.id" class="btn btn-danger">Sil</a> <a href="/Musteri/MusteriGetir/@item.id" class="btn btn-info">Güncelle</a></td>
            </tr>
        }
    </tbody>
</table>
@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa }))
<br />
<a href="/Musteri/YeniMusteri" class="btn btn-primary">Yeni Müşteri Ekle</a>
<a href="/Musteri/BakiyesizMusteriler" class="btn btn-warning">Bakiyesiz Müşteriler</a>

MvcStok/MvcStok/Views/Musteri/MusteriGetir.cshtml
@model MvcStok.Models.Entity.TblMusteriler
@{
    ViewBag.Title = "MusteriGetir";
    Layout = "~/Views/Shared/_adminlayout.cshtml";
}

<h1>Müşteri Güncelleme</h1>
@using (Html.BeginForm("MusteriGuncelle", "Musteri", FormMethod.Post))
{
    <label>Ad</label>
    @Html.TextBoxFor(m=>m.ad,new{ @class="form-control"})
    <br />

    <label>Soyad</label>
    @Html.TextBoxFor(m=>m.soyad,new{ @class="form-control"})
    
    <label>Şehir</label>
    @Html.TextBoxFor(m=>m.sehir,new{ @class="form-control"})
    
    <label>Bakiye</label>
    @Html.TextBoxFor(m=>m.bakiye,new{ @class="form-control"})
    
    @Html.HiddenFor(m=>m.id)
    <button class="btn btn-warning">Güncelle</button>
}

MvcStok/MvcStok/Views/Musteri/YeniMusteri.cshtml
@model MvcStok.Models.Entity.TblMusteriler
@{
    ViewBag.Title = "YeniMusteri";
    Layout = "~/Views/Shared/_adminlayout.cshtml";
}

<h1>Yeni Müşteri Ekleme</h1>
<form method="post">
    <label>Ad</label>
    @Html.TextBoxFor(m => m.ad, new {@class="form-control"})
    @Html.ValidationMessageFor(m => m.ad, "", new {@style="color:red"})
    <br />

    <label>Soyad</label>
    @Html.TextBoxFor(m => m.soyad, new {@class="form-control"})
    <br />

    <label>Şehir</label>
    @Html.TextBoxFor(m => m.sehir, new {@class="form-control"})
    <br />

    <label>Bakiye</label>
    <label class="form-control">0 ₺</label>
    <br />
    <button class="btn btn-success">Ekle</button>
</form>